#!/bin/bash

# Custom build for Docker Hub
# see: https://medium.com/microscaling-systems/labelling-automated-builds-on-docker-hub-f3d073fb8e1

cd ../..

apt-get install -y python3-pip
pip3 install pyyaml

# Build Graylog
docker build --build-arg VCS_REF="$(git rev-parse --short HEAD)" \
             --build-arg GRAYLOG_VERSION="$(./release.py --get-graylog-version)" \
             --build-arg BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
             --file docker/datanode/Dockerfile \
             --tag $IMAGE_NAME .
