#!/bin/bash

# Custom build for Docker Hub
# see: https://medium.com/microscaling-systems/labelling-automated-builds-on-docker-hub-f3d073fb8e1

cd ../..

docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
docker buildx create --name multiarch --driver docker-container --use
docker buildx inspect --bootstrap

# Build Graylog
docker build --platform linux/arm64/v8,linux/amd64 \
             --build-arg VCS_REF=$GIT_SHA1 \
             --build-arg GRAYLOG_VERSION=`cat VERSION` \
             --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
             --file docker/oss/Dockerfile \
             --tag $IMAGE_NAME \
             --push .
