#!/bin/bash

# Custom build for Docker Hub
# see: https://medium.com/microscaling-systems/labelling-automated-builds-on-docker-hub-f3d073fb8e1

cd ../..

apt-get install -y python3-pip
pip3 install pyyaml
cat version.yml | python3 -c 'import json, sys, yaml ; y=yaml.safe_load(sys.stdin.read()) ; print(json.dumps(y))'

# Build Graylog
docker build --build-arg VCS_REF=$GIT_SHA1 \
             --build-arg GRAYLOG_VERSION=`cat VERSION` \
             --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
             --file docker/oss/Dockerfile \
             --tag $IMAGE_NAME .
