#!/bin/bash

# Custom build for Docker Hub
# see: https://medium.com/microscaling-systems/labelling-automated-builds-on-docker-hub-f3d073fb8e1

cd ../..

# Build Graylog Forwarder
docker build --build-arg VCS_REF=$GIT_SHA1 \
             --build-arg GRAYLOG_FORWARDER_VERSION=`cat VERSION_FORWARDER` \
             --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
             --file docker/forwarder/Dockerfile \
             --tag $IMAGE_NAME .
