---
name: "DEV Container Images"

on:
  workflow_dispatch:

jobs:
  build:
    name: "Build"

    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        image:
          - file: "docker/datanode/Dockerfile"
            name: "graylog/graylog-datanode"
            context: "docker/datanode"
        arch:
          - name: "linux-x64"
            platform: "linux/amd64"
          - name: "linux-aarch64"
            platform: "linux/arm64"

    steps:
      - uses: "actions/checkout@v3"

      - name: "Set up QEMU"
        uses: "docker/setup-qemu-action@v2"

      - name: "Set up Docker Buildx"
        uses: "docker/setup-buildx-action@v2"

      - name: "Get and set ${{ matrix.arch.name }} snapshot URL"
        shell: "bash"
        run: |
          snapshot_url=$(curl -fsSL \
            -G -d limit=1 -d artifact=graylog-datanode-${{ matrix.arch.name }} \
            https://downloads.graylog.org/nightly-builds | \
            jq -r '.artifacts[].url')

          echo "SNAPSHOT_URL=$snapshot_url" | tee -a "$GITHUB_ENV"

      - name: "Login to Docker Hub"
        uses: "docker/login-action@v2"
        with:
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_PASSWORD }}"

      - name: "Build and push image: ${{ matrix.image.name }} - ${{ matrix.arch.name }}"
        uses: "docker/build-push-action@v4"
        with:
          context: "${{ matrix.image.context }}"
          platforms: "${{ matrix.arch.platform }}"
          pull: true
          push: true
          tags: "${{ matrix.image.name }}:dev"
          build-args: "SNAPSHOT_URL=${{ env.SNAPSHOT_URL }}"
