---
name: "DEV Container Images"

on:
  workflow_dispatch:
    inputs:
      snapshot_url_x64:
        description: "Snapshot URL - x64"
        required: true
      snapshot_url_aarch64:
        description: "Snapshot URL - aarch64"
        required: true

jobs:
  build:
    name: "Build"

    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        image:
          - file: "docker/datanode/Dockerfile"
            name: "graylog/graylog-datanode"
            context: "docker/datanode"

    steps:
      - uses: "actions/checkout@v3"

      - name: "Set up QEMU"
        uses: "docker/setup-qemu-action@v2"

      - name: "Set up Docker Buildx"
        uses: "docker/setup-buildx-action@v2"

      - name: "Login to Docker Hub"
        uses: "docker/login-action@v2"
        with:
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_PASSWORD }}"

      - name: "Build and push image: ${{ matrix.image.name }} - x64"
        uses: "docker/build-push-action@v4"
        with:
          context: "${{ matrix.image.context }}"
          platforms: "linux/amd64"
          pull: true
          push: true
          tags: "${{ matrix.image.name }}:dev"
          build-args: "SNAPSHOT_URL=${{ inputs.snapshot_url_x64 }}"

      - name: "Build and push image: ${{ matrix.image.name }} - aarch64"
        uses: "docker/build-push-action@v4"
        with:
          context: "${{ matrix.image.context }}"
          platforms: "linux/arm64"
          pull: true
          push: true
          tags: "${{ matrix.image.name }}:dev"
          build-args: "SNAPSHOT_URL=${{ inputs.snapshot_url_aarch64 }}"
